#!/bin/bash

# Galion Ecosystem Nginx Setup Script
# Automatically configures nginx reverse proxy for all services

set -e  # Exit on any error

echo "🚀 GALION ECOSYSTEM NGINX SETUP"
echo "==============================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root or with sudo"
    echo "Usage: sudo bash runpod-nginx-setup.sh"
    exit 1
fi

print_status "Checking prerequisites..."

# Check if nginx is installed
if ! command -v nginx &> /dev/null; then
    print_error "Nginx is not installed. Please install it first:"
    echo "sudo apt update && sudo apt install nginx -y"
    exit 1
fi

print_success "Nginx is installed"

# Create the nginx configuration
print_status "Creating nginx configuration..."

cat > /etc/nginx/sites-available/galion-ecosystem << 'EOF'
# Galion Ecosystem Nginx Configuration
# Automatically generated by runpod-nginx-setup.sh

# Upstream servers
upstream galion_backend {
    server localhost:8000;
}

upstream galion_studio {
    server localhost:3001;
}

upstream developer_platform {
    server localhost:3002;
}

upstream galion_app {
    server localhost:3003;
}

# Main server block
server {
    listen 80;
    server_name _;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # galion.studio - Corporate website
    location /studio/ {
        proxy_pass http://galion_studio;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # developer.galion.app - IDE platform
    location /developer/ {
        proxy_pass http://developer_platform;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # galion.app - Main voice AI platform
    location / {
        proxy_pass http://galion_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # API proxy - Backend services
    location /api/ {
        proxy_pass http://galion_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # CORS headers for API
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;

        # API-specific timeout settings
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
EOF

print_success "Nginx configuration created"

# Enable the site
print_status "Enabling nginx site..."

if [ -L "/etc/nginx/sites-enabled/galion-ecosystem" ]; then
    print_warning "Site already enabled, recreating symlink..."
    rm -f /etc/nginx/sites-enabled/galion-ecosystem
fi

ln -sf /etc/nginx/sites-available/galion-ecosystem /etc/nginx/sites-enabled/

# Remove default site
if [ -L "/etc/nginx/sites-enabled/default" ]; then
    print_status "Removing default nginx site..."
    rm -f /etc/nginx/sites-enabled/default
fi

print_success "Nginx site enabled"

# Test configuration
print_status "Testing nginx configuration..."
if nginx -t 2>/dev/null; then
    print_success "Nginx configuration is valid"
else
    print_error "Nginx configuration has errors!"
    nginx -t
    exit 1
fi

# Reload nginx
print_status "Reloading nginx..."
if nginx -s reload 2>/dev/null; then
    print_success "Nginx reloaded successfully"
else
    print_error "Failed to reload nginx!"
    exit 1
fi

# Verify nginx is running
print_status "Verifying nginx is running..."
if pgrep -x "nginx" > /dev/null; then
    print_success "Nginx is running"
else
    print_error "Nginx is not running!"
    exit 1
fi

# Test the configuration
print_status "Testing nginx endpoints..."
echo ""

# Test main endpoint
if curl -s --max-time 5 http://localhost/ > /dev/null 2>&1; then
    print_success "Main endpoint (galion.app) is accessible"
else
    print_warning "Main endpoint not accessible (services may not be running yet)"
fi

# Test studio endpoint
if curl -s --max-time 5 http://localhost/studio/ > /dev/null 2>&1; then
    print_success "Studio endpoint (/studio/) is accessible"
else
    print_warning "Studio endpoint not accessible (galion-studio may not be running)"
fi

# Test developer endpoint
if curl -s --max-time 5 http://localhost/developer/ > /dev/null 2>&1; then
    print_success "Developer endpoint (/developer/) is accessible"
else
    print_warning "Developer endpoint not accessible (developer-platform may not be running)"
fi

# Test API endpoint
if curl -s --max-time 5 http://localhost/api/health > /dev/null 2>&1; then
    print_success "API endpoint (/api/health) is accessible"
else
    print_warning "API endpoint not accessible (backend may not be running)"
fi

# Test health endpoint
if curl -s --max-time 5 http://localhost/health > /dev/null 2>&1; then
    print_success "Health check endpoint (/health) is working"
else
    print_warning "Health check endpoint not working"
fi

echo ""
print_success "NGINX SETUP COMPLETED SUCCESSFULLY!"
echo ""
echo "📋 NEXT STEPS:"
echo "=============="
echo "1. Start your services with PM2:"
echo "   pm2 start npm --name 'galion-studio' -- run start -- -p 3001"
echo "   pm2 start npm --name 'developer-platform' -- run start -- -p 3002"
echo "   pm2 start npm --name 'galion-app' -- run start -- -p 3003"
echo "   pm2 start python --name 'galion-backend' -- main_simple.py --host 0.0.0.0 --port 8000"
echo ""
echo "2. Expose ports in RunPod dashboard:"
echo "   Go to Settings → TCP Ports → Add: 80, 3001, 3002, 3003, 8000"
echo ""
echo "3. Test your ecosystem:"
echo "   curl http://[your-runpod-ip]/"
echo "   curl http://[your-runpod-ip]/studio/"
echo "   curl http://[your-runpod-ip]/developer/"
echo "   curl http://[your-runpod-ip]/api/health"
echo ""
echo "🎉 Your Galion ecosystem reverse proxy is ready!"
echo ""
echo "Script completed at: $(date)"
